<?php 
    return[
        "bd"=>[
            "host"=>"localhost:3306",
            "user"=>"root",
            "password"=>"",
            "database"=>"consultas",
            "charset"=>"utf-8"
        ]
    ];
?>